### ISSUE TITLE
Missing usage documentation

### ISSUE THREAD

**Issue by Dmitry-Kucher** [globocom/thumbor-distributed-collage-filter#1]
It would be awesome to have some more information about distributed collage filter usage.

Or can someone asks me what's wrong with my case:

```
https://thumbor-server/unsafe/filters:distributed_collage(horizontal,smart,/2015/12/5cLqDZXMM_o.jpg|/2015/12/5cLqDZXMM_o.jpg|/2015/12/5cLqDZXMM_o.jpg)/2015/12/5cLqDZXMM_o.jpg
```

I got an error `2018-04-14 21:53:36 thumbor:ERROR Retrieving at least one of the collaged images failed: not_found` but fallback image shows normally.

**Comment by thor27** [comment]
Hi!
Have you already figured this out? If not, could you try to use a full URL inside distributed_collage filter and see if it works?

Thanks!
